server:
  port: 8089

spring:
  cloud:
    #服务发现
    consul:
      port: 32158
      host: 106.13.10.5
      enabled: false
      discovery:
        #consul注册的主机地址
        hostname: micro-service.jcera
        catalogServicesWatch:
          enabled: false
        #consul健康检查的地址
        health-check-path: /actuator/health
        health-check-interval: 19s
        instance-id: ${spring.application.name}:${server.port}
        #该服务在consul上的分类标签
        tags: service
        #是否注册到consul上
        register: true


# springboot actuator 健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      #显示所有健康状态
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    db:
      #不检查DB，会导致的启动很慢的问题
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: true

